### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [grigorii-zander/zsh-npm-scripts-autocomplete#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by grigorii-zander** [comment]
Oh, I totally forgot about it!
Thank you for your suggestion, and thank you for being interested in adding it to your list! I hope someone will find it useful.
