### ISSUE TITLE
Add pnpm support

### ISSUE THREAD

**Issue by ai** [grigorii-zander/zsh-npm-scripts-autocomplete#2]
`pnpm` package manager has unique feature and used by big projects (Vue, PostCSS, etc).

It uses the same `package.scripts`. Seems like we just need to add `pnpm …` prefix.

Can we have `pnpm` support in this script for the glory of package manager diversity?

**Comment by grigorii-zander** [comment]
That's a good idea also to add the `pnpm` package manager, and it seems like the basic implementation is not hard to do, but I just noticed that they already have their own completion script, which also supports `package.scripts` (docs here https://pnpm.io/completion). And they also have an awesome package (https://github.com/pnpm/tabtab) that makes such autocompletion easier to make. So, it seems like these two shell extensions are going to conflict with each other, and I don't know if the integration (between my plugin and theirs) is worth it.
But sure, I'll add a basic integration.
