### ISSUE TITLE
How to troubleshoot

### ISSUE THREAD

**Issue by mattiasbonte** [grigorii-zander/zsh-npm-scripts-autocomplete#5]
Good day,

I've tried to install this mod but I can't seem to get it working.

Tools
- OS: Arch Linux
- Terminal 1: Kitty & Alacritty
- Terminal 2: Gnome-terminal

What have I tried:
- Uninstalling/reinstalling the plugin manually
- Tried with bare minimal `.zshrc` file and only this plugin active
- Reboot
- Different terminal emulator

Upon typing `npm run <tab>` nothing happens.

I was wondering if there is a way for me to troubleshoot further/more in depth besides the most common things which I've tried above?

Thanks!

**Comment by Tusko** [comment]
+1

**Comment by grigorii-zander** [comment]
sorry for the delay!
the issue is fixed now
